### ISSUE TITLE
Fix ability to use offscreenCanvasPonyfill in plugin

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-plugin-template#15]
This issue https://github.com/GMOD/jbrowse-plugin-template/issues/14 rightfully brought up that using our canvas offscreen canvas ponyfill has issues in the tsdx configuration since it checks webpack_require

**Comment by cmdcolin** [comment]
Note: The gwas plugin only works properly because it derives from linearwigglerenderer which initializes the offscreen canvas ponyfill, if a plugin wanted to use it directly, it would run into this issue

**Comment by tchannagiri** [comment]
I think its worth mentioning that checking webpack_require is a slightly separate issue. The compilation issue occurs because of require('canvas') library even though the code does doesn't use it in browser builds (umd/iife). The webpack_require check caused my build to choose the OffscreenCanvasPonyFill instead of browser OffscreenCanvas, but note that neither of these should really cause an error since they are both compatible with the browser (though choosing OffscreenCanvas would be better).

FWIW here is a dirty hack to fix this for any other plugin authors out there:

tsdx.config.js:
```
const globals = require('@jbrowse/core/ReExports/list').default
const { createJBrowsePluginTsdxConfig } = require('@jbrowse/development-tools')

module.exports = {
  rollup(config, options) {
    var config = createJBrowsePluginTsdxConfig(config, options, globals)
    if (options.format === 'umd' || options.format === 'iife') {
      // If it's an external package in node_modules and is not in JBrowse's
      // list of re-exported packages, bundle it in the UMD build.
      const originalExternal = config.external
      config.external = (...args) => {
        const isExternal = originalExternal(...args) || (args[0] == "canvas")
        return isExternal
      }
    }
    return config
  },
}
```
'canvas' is declared to be external for iife/umd builds and not compiled. You get a warning message from the compiler that no global name for 'canvas' has been declared, but it doesn't matter beause its not used at runtime.
