### ISSUE TITLE
canvas problem: Failed to compile Error: Unexpected character ' 

### ISSUE THREAD

**Issue by zhpn1024** [GMOD/jbrowse-plugin-template#22]
Hi,

I get an error when testing custom plugin for jbrowse2.

When running yarn start or npm run start, there are error messages:
......
⠹ Compiling modules...'http' is imported by node_modules/canvas/node_modules/simple-get/index.js, but could not be resolved – treating it as an external dependency
'https' is imported by node_modules/canvas/node_modules/simple-get/index.js, but could not be resolved – treating it as an external dependency
'http' is imported by http?commonjs-external, but could not be resolved – treating it as an external dependency
'https' is imported by https?commonjs-external, but could not be resolved – treating it as an external dependency
✖ Failed to compile
Error: Unexpected character ' (Note that you need plugins to import files that are not JavaScript)

at /home/zhangp/software/jbrowse-plugins/node_modules/canvas/build/Release/canvas.node:1:0

1:ELF>�T@��@8@▒▒��� ����$��$��  p�p�$p����$$P�td�M�M�M�
�
Q�tdGNU/)�ϼ/Z�Tf��o�jc|,�@
  �@"�"
   ^
2: @D0� @Ā�R
3: (��� �@      (�@��D)�!�      ��@"��@H@҂���d  @Hp �(%

xtermxtermxtermxtermxtermxtermpreferring built-in module 'url' over local alternative at '/home/zhangp/software/jbrowse-plugins/node_modules/url/url.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'querystring' over local alternative at '/home/zhangp/software/jbrowse-plugins/node_modules/querystring/index.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
......

I tried different versions of node and canvas but the errors are the same.

**Comment by garrettjstevens** [comment]
I think this is similar to another problem I've seen where the plugin is trying to bundle in a compiled dependency. A reproducible example would be the easiest for me to be able to debug, but if that's not possible it could be helpful to know what, if any, dependencies your plugin has and what imports you are using from `@jbrowse/core`.

It's possible this is the same as https://github.com/GMOD/jbrowse-plugin-template/issues/15, in which case the fix would be to use

```js
import { createCanvas, createImageBitmap } from '@jbrowse/core/util'

```
instead of 
```js
// don't use this one
// import { createCanvas, createImageBitmap } from '@jbrowse/core/util/offscreenCanvasPonyfill'
```

**Comment by zhpn1024** [comment]
OK. Let me try to find a way reproducing it.

**Comment by zhpn1024** [comment]
git clone https://github.com/GMOD/jbrowse-plugin-template

yarn init

rm yarn.lock

npm install

npm run start

// Up to now it works fine. Problem comes when I want to use BaseLinearDisplayComponent from '@jbrowse/plugin-linear-genome-view' for a custom display:

Ctrl C

npm install @jbrowse/plugin-linear-genome-view

npm run start

//Then add code of new dislay type with BaseLinearDisplayComponent  to src/index.ts:
......
import { BaseLinearDisplayComponent } from '@jbrowse/plugin-linear-genome-view'
......
return new DisplayType({
......
ReactComponent: BaseLinearDisplayComponent,
})
......

// When saving the code, the 'npm run start' session report the error.

**Comment by cmdcolin** [comment]
this is a tricky one, and it comes down to how to import stuff at runtime vs at compile time

it may be worth making a documentation and faq entry on this...seems it's not documented too well

one of our plugins, the gwas plugin, may be a good point of reference though


see here for an example of importing the baseLinearDisplayConfigSchema
https://github.com/cmdcolin/jbrowse-plugin-gwas/blob/master/src/LinearManhattanDisplay/index.ts#L1-L13

you could also import BaseLinearDisplayComponent in a similar way

**Comment by zhpn1024** [comment]
> this is a tricky one, and it comes down to how to import stuff at runtime vs at compile time
> 
> it may be worth making a documentation and faq entry on this...seems it's not documented too well
> 
> one of our plugins, the gwas plugin, may be a good point of reference though
> 
> see here for an example of importing the baseLinearDisplayConfigSchema
> https://github.com/cmdcolin/jbrowse-plugin-gwas/blob/master/src/LinearManhattanDisplay/index.ts#L1-L13
> 
> you could also import BaseLinearDisplayComponent in a similar way

Do you mean importing at runtime using getPlugin() function?
I'll try it. Thanks!

**Comment by cmdcolin** [comment]
@jbrowse/core no longer depends on node-canvas so this issue may be reduced now. It is still important to try to use runtime imports instead of static imports, and just for  ref (replying to the almost year old comment, yes, the getPlugin obtains the functions at runtime). using e.g.

import {blah} from '@jbrowse/plugin-linear-genome-view' is not recommended as that will bundle dependencies statically.

In some cases

import {blah} from '@jbrowse/core'
import {Component} from '@mui/material'

These will be rewritten by our rollup config to obtain the dependency at runtime instead of bundling it statically, but we don't use this to obtain re-exports from plugins currently
